score = int(input("Enter the score: "))
if score > 100 or score < 0: print(f"Wrong number")
elif score >= 90: print(f"A")
elif 82 <= score <= 89: print(f"B")
elif 74 <= score <= 81: print(f"C")
elif 64 <= score <= 73: print(f"D")
elif 60 <= score <= 63: print(f"E")
elif 35 <= score <= 59: print(f"FX")
elif score < 35: print(f"F")